server:
  port: 9527
spring:
  application:
    name: zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7000:7000/eureka/,http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    instance-id: zuul-gateway-9527
    prefer-ip-address: true
info:
  app.name: mirai-cloud
  company.name: mirai-Mars
  build.artifactId: $project.artifactId$
  build.version: $project.version$
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  routes:
    mydept.serviceId: micro-dept
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /mirai