server:
  port: 7002
eureka:
  instance:
    hostname:  eureka7002
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7000:7000/eureka/,http://eureka7001:7001/eureka/
