server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mirai.micro.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: micro-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///cloudDB03?serverTimezone=Asia/Shanghai&useSSL=FALSE
    username: root
    password: y973593589
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7000:7000/eureka/,http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    instance-id: micro-dept-8003
    prefer-ip-address: true
info:
  app.name: mirai-cloud
  company.name: mirai-Mars
  build.artifactId: $project.artifactId$
  build.version: $project.version$